language: R
cache: packages
sudo: false

addons:
   apt:
     packages:
       - libcurl4-openssl-dev
       - libxml2-dev
script:
- Rscript R/build.R
 
after_success:
- chmod a+x script/afterbuild
- script/afterbuild
