#!/usr/bin/env bash
set -e # halt script on error

#openssl aes-256-cbc -K $encrypted_953fb8c265a5_key -iv $encrypted_953fb8c265a5_iv -in publish-key.enc -out publish-key -d -out ~/.ssh/publish-key -d
#chmod u=rw,og= ~/.ssh/publish-key
#echo "Host github.com" >> ~/.ssh/config
#echo "  IdentityFile ~/.ssh/publish-key" >> ~/.ssh/config
git remote set-url origin git@github.com:fhcflx/freirepmp.git
git fetch origin -f master:master
